jobs:
  main:
    name: Validate PR title
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: amannn/action-semantic-pull-request@v5
name: Validate PR title
on:
  repository_dispatch:
    types: trigger-ga___pr-lint.yml
