jobs:
  build:
    name: Temurin ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        TZ: UTC
      name: Run all tests
      run: mvn -B spotless:check
    strategy:
      matrix:
        java:
        - '17'
name: pull-request-check
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
